version: "3.0"                     

services:  
  backend:
    env_file:
      - node/.env
    image: backend-node
    container_name: backend-node
    restart: always
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
     - ./node:/usr/src/app
     - /usr/src/app/node_modules
    ports:
     - 3000:3000